### ISSUE TITLE
Error in python/docker-compose.yml

### ISSUE THREAD

**Issue by rilma** [josiahcarlson/redis-in-action#96]
After making a fork of this repository and checkout out from master branch, I find the following error in Github Codespaces VM (Ubuntu 18.04.1; Docker Compose 1.29.2)

```sh
@rilma ➜ /workspaces/redis-in-action (task/python-qa) $ cd python/
@rilma ➜ /workspaces/redis-in-action/python (task/python-qa) $ docker-compose up -d
Recreating ddd071c4b215_redis-in-action-redis ... 
Recreating redis-in-action-python             ... 

Recreating redis-in-action-python             ... done

ERROR: for redis  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 941, in _get_container_create_options
  File "compose/service.py", line 1073, in _get_container_host_config
  File "docker/api/container.py", line 598, in create_host_config
  File "docker/types/containers.py", line 339, in __init__
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
[3226] Failed to execute script docker-compose
@rilma ➜ /workspaces/redis-in-action/python (task/python-qa) $
```

**Comment by rilma** [comment]
PR #97 is an attempt for a fix

**Comment by rilma** [comment]
PR #97 has been merged by @josiahcarlson 
Closing this issue
